apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-adult-income

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: adult-income-api
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
