name: MLOps CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-deploy-run:
    runs-on: [self-hosted, kubeflow]

    env:
      NAMESPACE: participant-17
      KFP_HOST: http://ml-pipeline-ui.kubeflow.svc.cluster.local:80
      KFP_NAMESPACE: kubeflow

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install kfp==2.*

      - name: Run tests
        run: |
          pytest -q || true

      - name: Compile Kubeflow Pipeline
        run: |
          python pipeline/compile.py

      - name: Deploy API to Kubernetes
        run: |
          kubectl -n $NAMESPACE apply -f k8s/deployment.yaml
          kubectl -n $NAMESPACE rollout status deploy/adult-income-api

      - name: Trigger Kubeflow Pipeline Run
        run: |
          python pipeline/run_kfp.py \
            --host $KFP_HOST \
            --pipeline-yaml pipeline/pipeline.yaml \
            --run-name auto-${GITHUB_SHA::7} \
            --experiment-name adult-income-ci \
            --namespace $KFP_NAMESPACE